### ISSUE TITLE
Work with laravel

### ISSUE THREAD

**Issue by hugofabricio** [falsandtru/pjax-api#19]
How to work with laravel, i define script but not work.

**Comment by falsandtru** [comment]
Can you show me the repro or error messages?

**Comment by hugofabricio** [comment]
no error message displays took a console.log and it returns the object normally.

**Comment by hugofabricio** [comment]
Its possible check in url: http://rpnonline.com.br

**Comment by falsandtru** [comment]
Thanks. The cause is default url validation. The current definition is

```ts
  public filter(el: HTMLAnchorElement): boolean {
    if (typeof el.href !== 'string') return false;
    const dest = new Url(el.href);
    return /^https?:$/.test(dest.protocol)
        && /^$|\.(html?|php)$/.test(dest.file);
  }
```

This validation rejects `/dir` pattern urls. So I'll fix it to allow its pattern.

**Comment by hugofabricio** [comment]
Thanks man :D

**Comment by falsandtru** [comment]
Now I unable to release the patched version because travis is broken. You can instantly fix this bug by setting the filter function instead of update.

```js
new Pjax({
  filter: () => true
});
```

**Comment by falsandtru** [comment]
Fixed, and released now.
