### ISSUE TITLE
Broke other scripts

### ISSUE THREAD

**Issue by hugofabricio** [falsandtru/pjax-api#21]
Hi,

I organize my code in modules and start other scripts in init.

example

```
// Common
window.mod.common = function() {

  // Scope
  var that = this;

  var init = function() {
    console.log('[brz] begin common.js');

    window.mod.navbar = new window.mod['navbar']();
    window.mod.mask = new window.mod['mask']();
    window.mod.radio = new window.mod['radio']();
    window.mod.player = new window.mod['player']();

  };
```

If access via browser or no pjax, the plugins works, but i use pjax, the plugins not instance, example window.mod.player and does not generate errors.

Have you ever had it?

**Comment by hugofabricio** [comment]
Solved. I call in pjax-ready

**Comment by falsandtru** [comment]
Okay, can you close this issue?
