### ISSUE TITLE
REQUEST: html/js/css only example

### ISSUE THREAD

**Issue by Buliwyfa** [falsandtru/pjax-api#24]
Hi,

Is there a way you provide an html/js/css only example.

I understand this is not optimal since all the page is requested all the time, but it may help me understand it better and integrated to any server environment.

Thanks

**Comment by falsandtru** [comment]
Is this?: https://github.com/falsandtru/pjax-api#demo

**Comment by Buliwyfa** [comment]
Thanks for your quick response.

Unfortunately, the extension used ts/.d.ts (for typescript I believe) make
no sense to me.

2017-02-17 13:30 GMT+01:00 falsandtru <notifications@github.com>:

**Comment by Buliwyfa** [comment]
Ok, I got the files I was missing something important... definitely today is not my day… I should go back to bed…

It does not work by just opening the files, it need a server to handle the ajax request… big LOL for my self

Thanks for your quick answer;)

Great work!!!

**Comment by falsandtru** [comment]
no problem.
