### ISSUE TITLE
QUESTION: How to update google analytcis

### ISSUE THREAD

**Issue by Buliwyfa** [falsandtru/pjax-api#25]
It's not clear to me :(  how can I update Google Analytics.

I guessing something like this:

Pjax.load({
  if (typeof ga === 'function') {
    ga('send', 'pageview', location.pathname);
  }
});

However, not sure how to call GA after the new content is loaded via Pjax

Thanks again!!

**Comment by seanthepottingshed** [comment]
$('.pjax-container').on('pJax:end', function() {
    ga('send', 'pageview', location.pathname);
});

**Comment by Buliwyfa** [comment]
thx

**Comment by seanthepottingshed** [comment]
Actually not sure if the above will work as it's for defunkt pjax

**Comment by falsandtru** [comment]
See #20
