### ISSUE TITLE
question:

### ISSUE THREAD

**Issue by Buliwyfa** [falsandtru/pjax-api#26]
When I try using links like:

$.pjax.click('demo.html')

I get an error: TypeError: $.pjax is undefined

Could I be missing a lib? If not, what can be the reason?

Thanks

**Comment by falsandtru** [comment]
Because this is not a jquery plugin.

**Comment by Buliwyfa** [comment]
Thanks for your quick answer.
ups... OK :)
How can you do something like that on this lib?
Thanks

**Comment by falsandtru** [comment]
See docs.
