### ISSUE TITLE
[Question] Config example to ignore url internal and external

### ISSUE THREAD

**Issue by victorpdiez** [falsandtru/pjax-api#27]
Hi, Thanks for this project.

I am sorry to ask but after reading the documentation and testing it and cannot configure Pjax to ignore some URL.

Could you please give an example configuration to ignore
 - '*/xx.php' (internal URL)
- 'maps.googleapis.com/*' (external url)

To disable ajax I have tried adding to config this:
```
scope: {
    '*/xx.php': undefined, // disable
    ' maps.googleapis.com/*': undefined, // disable
}
```
Which are the url I want PJAX disable.

Thanks a lot for your time an effort.

**Comment by falsandtru** [comment]
Hi,

- Paths need to start with root path `/`.
- External paths are already ignored. You don't need to write external paths in scope.

```ts
scope: {
    //'*/xx.php': undefined, // disable <- invalid
    '/xx.php': undefined, // disable <- valid
    //' maps.googleapis.com/*': undefined, // disable <- invalid
}
```
