### ISSUE TITLE
Not working on page with external Javascript

### ISSUE THREAD

**Issue by nanook21** [falsandtru/pjax-api#33]
I'm having a problem here:
http://hostonfiber.com/pjax-api/gh-pages/demo/basic/1.html

If you click 2 it goes directly to a page with an embedded Tweet and does not load it using PJAX.

Any ideas?

**Comment by falsandtru** [comment]
You seem to have failed to load twitter widgets.

```
Failed to load https://platform.twitter.com/widgets.js: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://hostonfiber.com' is therefore not allowed access.
```

You have to load it using jsonp instead. jQuery is good for this workaround.

**Comment by nanook21** [comment]
Thanks.

Do you know of a way to force all Ajax requests to be JSONP if CORS isn't set?

**Comment by falsandtru** [comment]
No. You have to use any wrapper library.

**Comment by falsandtru** [comment]
I'll fix this issue with the next version. However, it supports async scripts only.

**Comment by falsandtru** [comment]
Fixed.
