### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by saraer** [falsandtru/pjax-api#36]
version: v3.23.0
chrome: 最新版

### 再現方法
/page
でページを開いた後、
/page#name
にアクセスする。

### 結果
```Uncaught TypeError: Cannot read property 'title' of null```
が出ます。
ちなみに jquery版は問題ありませんでした。

**Comment by falsandtru** [comment]
おそらくhistory.stateを使う他のコードと競合しています。可能であれば検証可能なページを公開してください。

**Comment by saraer** [comment]
https://falsandtru.github.io/pjax-api/demo/basic/1.html
このページを開いた後、アドレスバーに #name と追加して更新すると再現できます。
念の為、タブがこれだけの状態で Chrome と Firefox でこちらでは再現できました。

**Comment by falsandtru** [comment]
把握しました。後ほど修正します。

**Comment by falsandtru** [comment]
修正しました。
