### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Jewel760** [falsandtru/pjax-api#37]
I am new to Github and I didn't find ways to thank you for creating this plugin and I came here in this issues option to thank you. I suddenly found your plugin in the WordPress repository and I downloaded it and it is definitely the best plugin and I am surprised why people didn't use it much. I was using smoothstate.js but I had a lot of issues with it and it was blocking all javascript. Pjax plugin that you have developed can be one of the best plugins on earth. Really amazing. I have added your plugin on my website and I am highly satisfied with this plugin. Please never stop development of this plugin.
my website is, https://novicecamp.com/

With thanks and regards,
Jewel

**Comment by falsandtru** [comment]
Thanks @Jewel760. The latest version would give you better experience (without IE). Cheers.
