### ISSUE TITLE
ファイルサイズの削減のお願い

### ISSUE THREAD

**Issue by tamaina** [falsandtru/pjax-api#38]
はじめまして。このpjaxライブラリは機能が豊富なため、便利に使わせていただいております。

しかしながら、ひとつ非常に大きな問題点があるため、今回、表題の通りのIssueを立てさせていただきました。  
このライブラリは、minifyされたものでもファイルサイズが420kb程ありますが、これはあまりに大きすぎるのではないでしょうか。  

このライブラリの処理過程についてあまり深くは追えていないため、含まれるすべてが必要なコードであるなら申し訳なく思います。  
しかしながら、バンドルサイズの削減、もしくは機能を削減したバージョンの作成などをご検討いただけますと有難く思います。どうかよろしくお願いいたします。

**Comment by falsandtru** [comment]
ファイルサイズの増加はIntegrityチェックのために追加された<https://www.npmjs.com/package/ssri>により生じておりWeb標準のセキュリティ機能への対応であるため削除は難しいです。gzip後はminify前でも178 KB(<http://falsandtru.github.io/pjax-api/>)とさほど大きくないのでgzipすれば実用上問題ないかと思います。

**Comment by tamaina** [comment]
すでにgzip後に178KBあるのは若干大きいという感覚を持ちますが、セキュリティ上必要な処理ということですので減らすわけにもいきませんよね。  
ありがとうございました。

**Comment by falsandtru** [comment]
最新版でチェック処理をFetchAPIに委譲し未圧縮で99KBまで削減しました。
