### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by Jewel760** [falsandtru/pjax-api#39]
I have added your pjax plugin from wordpress repository and it is working fine but I have found some issues, php/javascripts are not working from the other plugins and some plugins are also not working properly. I don't know how to fix this.
I want to add Pjax-api that you have added here and I want to add it to Wordpress. How to integrate it?

Thank you once again for making a great plugin. All the best.

**Comment by falsandtru** [comment]
Unfortunately I ended the support of that plugin.
