### ISSUE TITLE
IE11 support - will running through babel solve it?

### ISSUE THREAD

**Issue by Yahav** [falsandtru/pjax-api#41]
At the docs it states ES6 requirement, it doesn't specify which elements of ES6 are used.
I wonder whether running it through babel will provide IE11 support.

**Comment by falsandtru** [comment]
Anyway IE11 has a lot of bugs and I don't resolve it.

**Comment by Yahav** [comment]
Even an ES6 polyfill generated by polyfill.io won't work here?
This subject should at least be discussed. at current time IE11 support is still widely requested.

**Comment by falsandtru** [comment]
> Even an ES6 polyfill generated by polyfill.io won't work here?

I don't mean lack of modern APIs. So it doesn't help the problem.

**Comment by Yahav** [comment]
So? what is the problem?

**Comment by falsandtru** [comment]
Polyfill also won't be a solution.
