### ISSUE TITLE
Adding more events, preventing unload on condition

### ISSUE THREAD

**Issue by georgehristov** [falsandtru/pjax-api#42]
Have you considered adding more events to the list (as in defunkt/jquery-pjax)?
Is there a way to prevent request in case some conditions not met? For instance a dirty form not saved.

**Comment by falsandtru** [comment]
Probably you should call event.preventDefault().

**Comment by georgehristov** [comment]
Tried it put it did not work as expected.
And in any case it is better for have the pjax:click and pjax:clicked events to prevent even sending the request to the server

**Comment by falsandtru** [comment]
However, anyway there is no way to prevent browser back/forward without handling unload events. And since pjax usually disables browser functions to keep form data, I don't use pjax with form pages and I recommend that pjax users do so.
