### ISSUE TITLE
Ajax POST method become GET

### ISSUE THREAD

**Issue by ljfreelancer88** [falsandtru/pjax-api#43]
I have a link which deletes a record and I'm using Ajax & POST method. But PJAX "converted" it to GET method. Is there any way to tell PJAX in the API to exclude elements?

This is the simple code.
```
<a href="...">delete</a><!-- This link trigged by POST method AJAX -->

<div class="card-body">
<div id="pjax-container">
...content
</div>
</div>

new Pjax({
  areas: [
    '.card-body',
    '#pjax-container'
  ]
});
```

**Comment by falsandtru** [comment]
Use link or filter option. But anyway anchor links don't support non-idempotent methods.
