### ISSUE TITLE
I can not request same url after upgrading from 3.35.3 to 3.38.1

### ISSUE THREAD

**Issue by scil** [falsandtru/pjax-api#53]
why I need requesting same url?  because my login form would make a fake url '/user/login'.

say I am at homepage '/', then click user login btn, url is '/user/login', then I click homepage logo, the url should become '/', but it does not change, remaining 'user/login'

I have not found any config about this. 

so what can i do to allow request the same url?

**Comment by falsandtru** [comment]
Cannot reproduce the problem from your info. Can you show me a demo? And can you identify the version that caused the problem, like 3.35.3 to 3.35.4?

**Comment by scil** [comment]
> Cannot reproduce the problem from your info. Can you show me a demo? And can you identify the version that caused the problem, like 3.35.3 to 3.35.4?

Thank you. 

my website performed well with 3.35.3

recently I upgrade pjax-api to 3.38.1 and today I found that i can not request the same url

**Comment by scil** [comment]
now I downgrade to 3.35.3,   everything go very.

I guess the new version of pjax-api maybe take a check and render the new document only when the new url is different

**Comment by falsandtru** [comment]
Too little info for debugging.
