### ISSUE TITLE
encode url and %

### ISSUE THREAD

**Issue by zzzazzz** [falsandtru/pjax-api#54]
Hi, I have a strange bug on this latest version.
For the internal search engine on my site, I have an uri of the following form: `?page=search&search=hit the fan` (via a form sent using the get method)
I'm expecting to see `hit%20the%20fan` (although normally my search engine works with `hit+the+fan`). Anyway, I see in the uri: `hit%25252520the%25252520fan`. As if `encode(url)` was repeated 4 times? Any ideas? A setting I don't understand? 
Thanks a lot.

**Comment by falsandtru** [comment]
v3.38.4 should fix it.

**Comment by zzzazzz** [comment]
Wow, this seems to work well, and is served quickly ;) Thank you very much !
