### ISSUE TITLE
Config to prevent the link from being changed automatically

### ISSUE THREAD

**Issue by mohammad-hashem-foo** [falsandtru/pjax-api#55]
How I can prevent the link from being changed automatically when using assign method

`Pjax.assign('/?refresh=1', {
    areas: ["#mainContent"],
    fetch: {
        timeout: 60000,
    },
});`

**Comment by mohammad-hashem-foo** [comment]
When using pjax the url in the browser updated automatically 
is there a way to not change the url

**Comment by falsandtru** [comment]
No. Pjax is not a tool for updates. Use ajax instead.
