### ISSUE TITLE
Script reloads every time?

### ISSUE THREAD

**Issue by yangy9593** [falsandtru/pjax-api#56]
Hello, in this example, about.js will be executed when about.html is loaded for the first time, and will not be executed again after that. How to make it execute every time? Thank you (from Google Translate)

https://codesandbox.io/s/nostalgic-violet-gc4hhh?file=/index.html

**Comment by falsandtru** [comment]
Use the reload option.

https://falsandtru.github.io/pjax-api/docs/apis/pjax/config/
