### ISSUE TITLE
Cannot find module 'spica/dict' or its corresponding type declarations

### ISSUE THREAD

**Issue by EnixCoda** [falsandtru/pjax-api#57]
If use `pjax-api` in TypeScript projects, there will would type error `Cannot find module 'spica/dict' or its corresponding type declarations` raised from `node_modules/pjax-api/index.d.ts` due to no installation of `spica` at all. Because `spica` is listed in `devDependencies` instead of `dependencies` in `package.json`. IMO it is against the convention of npm package dependency management.

https://github.com/falsandtru/pjax-api/blob/b906ecae90b19a852f245460d34b10500bf5ec0f/index.d.ts#L1

Would you please declare it in `dependencies` field?

**Comment by falsandtru** [comment]
Fixed.
