### ISSUE TITLE
如何手动触发pjax

### ISSUE THREAD

**Issue by kannafay** [falsandtru/pjax-api#59]
你好，我看到你的配置项中有个fetch，不知道他是不是手动触发pjax的关键，但是我尝试了很多次都没能成功。
大佬可以给一个手动触发pjax的方法吗，因为在项目中有一个span标签，他的`data-href`为`http://xxx.com`。当点击的元素时则无法正常触发pjax行为，所以我想在点击span时正常触发pjax行为。

**Comment by falsandtru** [comment]
Use English.
